# Generated by Django 3.2 on 2022-08-20 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20220809_1216'),
        ('noticias', '0003_auto_20220809_1348'),
    ]

    operations = [
    ]
