# Generated by Django 3.2 on 2022-08-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('es_gratuito', models.BooleanField()),
                ('es_presencial', models.BooleanField()),
                ('ubicacion', models.CharField(max_length=120)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos', verbose_name='Imagen opcional')),
            ],
        ),
    ]
