# Generated by Django 3.2 on 2022-08-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20220810_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.CharField(blank=True, default='Botellas de Amor', max_length=50, null=True),
        ),
    ]
