# Generated by Django 3.2 on 2022-09-01 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0008_comentario_contenido_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='contenido_num',
        ),
    ]
