# Generated by Django 3.2 on 2022-08-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0003_alter_formulario_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='contactos', verbose_name='imagen opcional'),
        ),
    ]
