# Generated by Django 3.2 on 2022-08-22 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0004_formulario_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formulario',
        ),
    ]
